spring.application.name=service-b
server.port=8084

app.jwt.secret=mySecretKeyForJwtTokenGenerationThatShouldBeLongEnoughAndSecure12345

# Eureka client
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.preferIpAddress=true
